SRC = cxform.c

IDL_EXT=$(IDL_DIR)/external

CFLAGS=-Wall -fPIC -shared -I$(IDL_EXT)

all:		cxform.so

cxform.so:	cxform-auto.o  cxform-manual.o  cxform-dlm.o
	ld -G -o $@ $^


test:	test.o  cxform-auto.o  cxform-manual.o
	cc -o $@ $^ -lm

clean:
	rm -f *.so *.sl *.o core a.out


#
# DEVELOPERS ONLY: much of this package (cxform-auto.c, cxform.dlm) is
# automatically generated by Perl scripts.  For the distribution,
# though, this isn't really necessary: most people won't be adding
# new functions, or mucking about with other stuff.  It does simplify 
# things quite a bit to leave that stuff out.
#
# **************     **************     **************     **************
# ***  NOTE  ***     ***  NOTE  ***     ***  NOTE  ***     ***  NOTE  ***
# **************     **************     **************     **************
#
# The "-include" should fail silently if it cannot find Makefile.develop
# However, if you get the following error:
#
#  make: Fatal error in reader: Makefile, line 80: Unexpected end of line seen
#
# ...it's because you're using Solaris make, which is pathetically
# obsolete.  Please upgrade to GNU make <ftp://gnu.mit.edu/pub/gnu/make/>,
# or, if you're lazy and/or in a hurry, just comment out the following
# line by prepending a "#" before the "-include".
-include Makefile.develop
